### Content Based Recommendation System

In [1]:
import pandas as pd

df = pd.read_csv('2 - movies_metadata - Content based Recommendation.csv')

In [2]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",http://www.womenartrevolution.com/,55245,tt1699720,en,!Women Art Revolution,"Through intimate interviews, provocative art, ...",...,01-01-2010,0,83.0,[],Released,40 years in the making!,!Women Art Revolution,False,4.3,2
1,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,41371,tt1637976,en,#1 Cheerleader Camp,A pair of horny college guys get summer jobs a...,...,27-07-2010,0,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Grab your spirit sticks!,#1 Cheerleader Camp,False,3.4,23
2,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",http://www.chicagogirlfilm.com/,267752,tt3060338,en,#chicagoGirl,From her childhood bedroom in the Chicago subu...,...,21-11-2013,0,74.0,[],Released,The Social Network Takes on a Dictator,#chicagoGirl,False,7.0,1
3,False,NaN,1500000,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",http://www.hashtaghorror.com/,301325,tt3526286,de,#Horror,"Inspired by actual events, a group of 12 year ...",...,20-11-2015,0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Death is trending.,#Horror,False,3.4,53
4,False,NaN,0,"[{'id': 37, 'name': 'Western'}]",NaN,143747,tt0060697,it,Mille dollari sul nero,Johnny Liston has just been released from pris...,...,18-12-1966,0,104.0,"[{'iso_639_1': 'it', 'name': 'Italiano'}, {'is...",Released,NaN,"$1,000 on the Black",False,6.0,2

In [3]:
df['tagline'].fillna('')
df['description'] = df['overview'] + df['tagline']
# df['description'] = df['description'].fillna('')

In [4]:
df.shape

(45380, 25)

In [5]:
df.dropna(subset=['title'], inplace=True)
df.dropna(subset=['description'], inplace=True)
df['title'].drop_duplicates(inplace=True)

In [6]:
df.shape

(20363, 25)

In [7]:
df.reset_index()

,index,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,description
0,0,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",http://www.womenartrevolution.com/,55245,tt1699720,en,!Women Art Revolution,...,0,83.0,[],Released,40 years in the making!,!Women Art Revolution,False,4.3,2,"Through intimate interviews, provocative art, ..."
1,1,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,41371,tt1637976,en,#1 Cheerleader Camp,...,0,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Grab your spirit sticks!,#1 Cheerleader Camp,False,3.4,23,A pair of horny college guys get summer jobs a...
2,2,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",http://www.chicagogirlfilm.com/,267752,tt3060338,en,#chicagoGirl,...,0,74.0,[],Released,The Social Network Takes on a Dictator,#chicagoGirl,False,7.0,1,From her childhood bedroom in the Chicago subu...
3,3,False,NaN,1500000,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",http://www.hashtaghorror.com/,301325,tt3526286,de,#Horror,...,0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Death is trending.,#Horror,False,3.4,53,"Inspired by actual events, a group of 12 year ..."
4,6,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,4204,tt1024733,en,$5 a Day,...,0,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Relationships don't come cheap!,$5 a Day,False,6.0,24,"After being released from jail, the son of a c..."
5,10,False,NaN,7500000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://500days.com,19913,tt1022603,en,(500) Days of Summer,...,60722734,95.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,It was almost like falling in love.,(500) Days of Summer,False,7.2,2993,"Tom (Joseph Gordon-Levitt), greeting-card writ..."
6,14,False,NaN,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 99, 'n...",NaN,318972,tt4370922,en,(T)ERROR,...,0,93.0,[],Released,Under Cover. Under Threat.,(T)ERROR,False,6.8,12,After working for more than 20 years as a coun...
7,15,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,45261,tt1132193,en,(Untitled),...,230600,96.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Everyone's got an opinion.,(Untitled),False,6.6,16,A fashionable contemporary art gallerist in Ch...
8,16,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,30709,tt0081964,en,...All the Marbles,...,0,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The California Dolls and their best friend Har...,...All the Marbles,False,7.3,7,A two-bit promoter tries to take a women's wre...
9,17,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,8420,tt0049189,fr,Et Dieu… créa la femme,...,0,95.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,...but the devil invented Brigitte Bardot!,...And God Created Woman,False,6.2,43,"Juliette Hardy is sexual dynamite, and has the..."
10,21,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,41091,tt0381838,ko,...ing,...,0,104.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,The Happiest Time of My Life,...ing,False,6.6,17,Follows the life of a young woman (Min-ah) who...
11,22,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,85255,tt0065360,en,...tick... tick... tick...,...,0,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Two men with nothing in common but the hate th...,...tick... tick... tick...,False,6.2,7,Racial tensions threaten to explode when a bla...
12,24,False,NaN,0,"[{'id': 16, 'name': 'Animation'}, {'id': 53, '...",NaN,72478,tt1808454,pl,Sala samobójców,...,0,110.0,"[{'iso_639_1': 'pl', 'name': 'Polski'}]",Released,Where fantasy and reality meet.,@Suicide Room,False,7.7,113,Dominik is an ordinary boy. He's got loads of ...
13,25,False,"{'id': 74508, 'name': '[REC] Collection', 'pos...",1500000,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",http://www.3l-filmverleih.de/rec,8329,tt1038988,es,[REC],...,30448000,78.0,"[{'iso_639_1': 'ja', 'name': '日本語'}, {'iso_639...",Released,One witness. One camera,[REC],False,7.1,954,A television reporter and cameraman follow eme...
14,26,False,"{'id': 74508, 'name': '[REC] Collection', 'pos...",0,"[{'id': 53, 'name': 'Thriller'}, {'id': 27, 'n...",http://rec4apocalipsis.com/,185341,tt1649443,es,[REC] 4: Apocalipsis,...,190000,95.0,"[{'iso_639_1': 'es', 'name': 'Español'}]",Released,It's time to leave.,[REC]⁴ Apocalypse,False,5.2,269,Ángela Vidal the young television reporter who...
15,27,False,"{'id': 74508, 'name': '[REC] Collection', 'pos...",5600000,"[{'id': 53, 'name': 'Thriller'}, {'id': 27, 'n...",http://www.rec2themovie.com/,10664,tt1245112,es,[REC]²,...,18469680,85.0,"[{'iso_639_1': 'es', 'name': 'Español'}]",Released,Fear Revisited,[REC]²,False,6.5,496,"The action continues from [REC], with the medi..."
16,28,False,"{'id': 74508, 'name': '[REC] Collection', 'pos...",0,"[{'id': 27, 'name': 'Horror'}]",http://www.magnetreleasing.com/rec3/,80280,tt1649444,es,[REC]³ Génesis,...,10158000,80.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,You may kiss the bride.,[REC]³ Genesis,False,4.9,360,The action now takes place miles away from the...
17,29,False,"{'id': 265709, 'name': '00 Schneider Filmreihe...",0,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,1652,tt0109000,de,00 Schneider - Jagd auf Nihil Baxter,...,0,92.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,Verbrechen lohnt sich wieder,00 Schneider - Jagd auf Nihil Baxter,False,6.5,16,The funny clown Bratislav Metulskie is found d...
18,32,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",NaN,259300,tt3008816,ja,009ノ1（ゼロゼロクノイチ） THE END OF THE BEGINNING,...,0,82.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,She was forced to become the perfect killing m...,009-1: The End of the Beginning,False,3.5,3,"Marking the 75th anniversary of his birth, Sho..."
19,36,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,342472,tt2184233,en,1 Mile to You,...,0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Run with your heart.,1 Mile to You,False,6.7,29,"After a teenager's friends die in an accident,..."
20,37,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",http://level33entertainment.com/1_Night.html,416691,tt4126694,en,1 Night,...,0,76.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Love can happen at any time.,1 Night,False,6.2,30,Thirty-something Elizabeth must decide whether...
21,43,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,346592,tt2134170,en,10 Cent Pistol,...,0,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Never try to outsmart a wiseguy.,10 Cent Pistol,False,4.4,7,A story about two lifelong criminals who maneu...
22,44,False,NaN,15000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 878, '...",http://www.10cloverfieldlane.com/,333371,tt1179933,en,10 Cloverfield Lane,...,108286421,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Monsters come in many forms.,10 Cloverfield Lane,False,6.8,2537,"After a car accident, Michelle awakens to find..."
23,46,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,2357,tt0499603,en,10 Items or Less,...,580527,81.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Sometimes in life you have to change lanes.,10 Items or Less,False,6.6,50,An actor who is considering the role of a supe...
24,52,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,216138,tt1993391,en,10 Rules for Sleeping Around,...,0,94.0,"[{'iso_639_1': 'es', 'name': 'Español'}, {'iso...",Released,Now it's our turn.,10 Rules for Sleeping Around,False,3.9,23,"By following ten simple rules, 20-somethings ..."
25,53,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,4951,tt0147800,en,10 Things I Hate About You,...,53478166,97.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,How do I loathe thee? Let me count the ways.,10 Things I Hate About You,False,7.3,1768,"Bianca, a tenth grader, has never gone on a da..."
26,54,False,NaN,4520000,"[{'id': 27, 'name': 'Horror'}, {'id': 80, 'nam...",NaN,18587,tt0085121,en,10 to Midnight,...,7175592,101.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A cop... A killer... A deadline.,10 to Midnight,False,6.1,37,"Based on the real-life Richard Speck murders, ..."
27,55,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,58547,tt1715873,en,10 Years,...,201146,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Who Got Fat? Who Didn't Change? Who Got Rich? ...,10 Years,False,5.7,161,A group of friends reunite ten years after the...
28,57,False,NaN,105000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",NaN,7840,tt0443649,en,"10,000 BC",...,266000000,109.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The legend. The battle. The first hero.,"10,000 BC",False,5.1,934,A prehistoric epic that follows a young mammot...
29,62,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 12, 'name...",NaN,302666,tt3488056,en,10.0 Earthquake,...,0,88.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The end is near.,10.0 Earthquake,False,4.3,28,Los Angeles is about to be hit by a devastatin...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20333,45328,False,NaN,0,"[{'id': 27, 'name': 'Horror'}]",NaN,22130,tt0081027,fr,Le lac des morts vivants,...,0,87.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,God help us if they rise again!,Zombie Lake,False,3.2,18,"In a small village, somewhere in France, Germa..."
20334,45329,False,NaN,1000000,"[{'id': 27, 'name': 'Horror'}]",NaN,219247,tt2978716,en,Zombie Night,...,0,88.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Tonight, at sundown... the dead will rise again",Zombie Night,False,3.4,20,Zombies come out at night and two families mus...
20335,45331,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 27, 'nam...",NaN,364153,tt3397948,en,Zombie Ninjas vs Black Ops,...,0,94.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"What doesn't kill you, will try and try again.",Zombie Ninjas vs Black Ops,False,0.0,0,In the clandestine research tower of a ruthles...
20336,45332,False,NaN,0,"[{'id': 27, 'name': 'Horror'}, {'id': 35, 'nam...",https://www.facebook.com/zombiepizza.themovie/,434661,tt3793632,en,Zombie Pizza,...,0,94.0,[],Released,Pizza. Anytime. Anywhere.,Zombie Pizza,False,9.3,2,"After losing his father, a teenage boy decides..."
20337,45333,False,NaN,0,"[{'id': 27, 'name': 'Horror'}]",NaN,128264,tt1462677,en,Zombie Reanimation,...,0,86.0,[],Released,You cant kill what is dead,Zombie Reanimation,False,2.0,1,It all started with the first Zombie infection...
20338,45334,False,NaN,0,"[{'id': 27, 'name': 'Horror'}]",http://www.charmed-apocalypse.com/,332488,tt2267454,en,Zombie Resurrection,...,0,79.0,[],Released,Prey for salvation,Zombie Resurrection,False,4.4,6,"15 months after the apocalypse, a group of sur..."
20339,45335,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...",NaN,13009,tt0960890,en,Zombie Strippers!,...,0,94.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Live Dead Nudes,Zombie Strippers!,False,4.3,80,In the not too distant future a secret governm...
20340,45336,False,NaN,0,"[{'id': 27, 'name': 'Horror'}]",http://www.zombieundead.com/,65871,tt1581839,en,Zombie Undead,...,0,79.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Prepare for a new breed,Zombie Undead,False,2.0,3,A car roars through the darkened country roads...
20341,45338,False,NaN,23600000,"[{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...",http://www.zombieland.com/,19908,tt1156398,en,Zombieland,...,102391382,88.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,This place is so dead,Zombieland,False,7.2,3655,Columbus has made a habit of running from what...
20342,45339,False,NaN,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,38120,tt0051226,en,Zombies of Mora Tau,...,0,70.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Zombies of the African Voodoo coast!,Zombies of Mora Tau,False,5.8,7,"American tycoon George Harrison, his beautiful..."
20343,45340,False,NaN,0,"[{'id': 878, 'name': 'Science Fiction'}]",NaN,118636,tt0045352,en,Zombies of the Stratosphere,...,0,167.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,YOU'LL SAY...AMAZING!...STARTLING!...UNBELIEVE...,Zombies of the Stratosphere,False,4.5,2,Martians come to Earth to build an H-bomb stro...
20344,45341,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,30183,tt0038270,en,Zombies on Broadway,...,0,69.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Hee! Hee! What ghoulish glee!,Zombies on Broadway,False,4.7,6,Hiring real zombies for a broadway show proves...
20345,45343,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 27, 'nam...",NaN,105989,tt1043585,en,Zombi: La creazione,...,0,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"When the dead first walked, they had no time f...",Zombies: The Beginning,False,6.0,2,A woman floating on a raft in the middle of th...
20346,45344,False,NaN,0,"[{'id': 27, 'name': 'Horror'}]",http://www.zombieworldmovie.com,319396,tt3717324,en,Zombieworld,...,0,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The end is HERE!,Zombieworld,False,5.2,8,There is nowhere to hide...nowhere to run...th...
20347,45348,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,17790,tt0092298,en,Zone Troopers,...,0,86.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,They Take War To A New Dimension.,Zone Troopers,False,3.6,10,"American soldiers, led by The Sarge, are stuck..."
20348,45351,False,NaN,80000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.zookeeper-movie.com/,38317,tt1222817,en,Zookeeper,...,169852759,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Welcome to his jungle.,Zookeeper,False,5.3,509,A comedy about a zookeeper who might be great ...
20349,45352,False,"{'id': 352789, 'name': 'Zoolander Collection',...",28000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,9398,tt0196229,en,Zoolander,...,60780981,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,3% Body Fat. 1% Brain Activity.,Zoolander,False,6.1,1363,"Clear the runway for Derek Zoolander, VH1's th..."
20350,45353,False,"{'id': 352789, 'name': 'Zoolander Collection',...",50000000,"[{'id': 35, 'name': 'Comedy'}]",http://www.zoolander.com/,329833,tt1608290,en,Zoolander 2,...,55969000,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Long time no Z,Zoolander 2,False,4.7,814,Derek and Hansel are modelling again when an o...
20351,45354,False,NaN,0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",NaN,405670,tt5133392,ru,Зоология,...,0,87.0,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",Released,It's Never Too Late To Grow A Tail,Zoology,False,7.0,7,"Natasha is a lonely, middle-aged admin employe..."
20352,45355,False,NaN,35000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",NaN,14113,tt0383060,en,Zoom,...,12506188,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They're going to save the world... as long as ...,Zoom,False,4.9,140,Jack Shepard is an out-of-shape auto shop owne...
20353,45357,False,NaN,0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",NaN,385320,tt5340882,en,Zoombies,...,0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"Uncaged, Undead",Zoombies,False,3.9,32,When a strange virus quickly spreads through a...
20354,45358,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,76397,tt0083365,en,Zoot Suit,...,0,103.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,An american original.,Zoot Suit,False,6.9,4,"Part fact and part fiction, Zoot Suit is the f..."
20355,45359,False,NaN,150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",http://movies.disney.com/zootopia,269149,tt2948356,en,Zootopia,...,1023784195,108.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Welcome to the urban jungle.,Zootopia,False,7.7,4961,"Determined to prove herself, Officer Judy Hopp..."
20356,45361,False,NaN,783000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",NaN,10604,tt0057831,el,Αλέξης Ζορμπάς,...,0,142.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Life. Lust. Love. Zorba.,Zorba the Greek,False,7.0,55,An uptight English writer traveling to Crete o...
20357,45363,False,"{'id': 1657, 'name': 'Zorro Collection', 'post...",0,"[{'id': 37, 'name': 'Western'}, {'id': 35, 'na...",NaN,18450,tt0072448,fr,Zorro,...,0,124.0,"[{'iso_639_1': 'it', 'name': 'Italiano'}]",Released,Zorro is back!,Zorro,False,7.0,17,A newly arrived governor finds his province un...
20358,45364,False,NaN,0,"[{'id': 37, 'name': 'Western'}, {'id': 28, 'na...",NaN,19317,tt0083366,en,"Zorro, The Gay Blade",...,0,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Zexy, Zany, Zensational !","Zorro, The Gay Blade",False,5.4,15,George Hamilton stars in a dueling dual role a...
20359,45365,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",NaN,74924,tt0056725,en,Zotz!,...,0,87.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Zay It, Zee It and Zoon!",Zotz!,False,6.5,2,"Jonathan Jones, a professor of ancient languag..."
20360,45370,False,"{'id': 374386, 'name': 'Anglo-Zulu War Collect...",3500000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,14433,tt0058777,en,Zulu,...,8000000,138.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Dwarfing the mightiest! Towering over the grea...,Zulu,False,7.4,137,"In 1879, during the Zulu wars, man of the peop..."
20361,45372,False,"{'id': 374386, 'name': 'Anglo-Zulu War Collect...",0,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",NaN,18061,tt0080180,en,Zulu Dawn,...,0,117.0,"[{'iso_639_1': 'zu', 'name': 'isiZulu'}, {'iso...",Released,The sun dawned bloodied...two great armies met...,Zulu Dawn,False,5.6,35,"In 1879, the British suffer a great loss at th..."
20362,45378,False,NaN,2000000,"[{'id': 53, 'name': 'Thriller'}]",NaN,41393,tt0429277,en,Zyzzyx Road,...,30,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Dead Ahead,Zyzzyx Road,False,4.0,4,A married man (Leo Grillo) meets a beautiful w...

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(analyzer='word', ngram_range=(1, 3), min_df=0, stop_words='english')
tfidf_matrix = tf.fit_transform(df['description'])
print(tfidf_matrix)

  (0, 540281)	0.07863794639487151
  (0, 539938)	0.07032097415941656
  (0, 840039)	0.08787972512329106
  (0, 59144)	0.2580344826308387
  (0, 855484)	0.07685208204033515
  (0, 493498)	0.08238218222963276
  (0, 384062)	0.04243573296725953
  (0, 1126780)	0.07194201154982238
  (0, 400870)	0.07072659051419122
  (0, 375471)	0.06925379806353062
  (0, 294065)	0.05615003901413311
  (0, 885265)	0.07339894465544233
  (0, 21206)	0.10507405008723673
  (0, 813881)	0.06688240955307218
  (0, 209850)	0.07097677671232364
  (0, 288605)	0.10367438651643612
  (0, 1129539)	0.06521377528135952
  (0, 378708)	0.09842390876889619
  (0, 886902)	0.07279457346163164
  (0, 850930)	0.09930456385094111
  (0, 1082684)	0.08153300638579772
  (0, 236764)	0.07250353674037269
  (0, 1068007)	0.06585339542203213
  (0, 8827)	0.07946929266975768
  (0, 1185221)	0.04332284785822668
  :	:
  (20362, 609825)	0.11973255528434235
  (20362, 456625)	0.11973255528434235
  (20362, 89883)	0.11973255528434235
  (20362, 1166463)	0.11973255528434235
  (20362, 572849)	0.11973255528434235
  (20362, 481658)	0.11973255528434235
  (20362, 1122610)	0.11973255528434235
  (20362, 154711)	0.11973255528434235
  (20362, 37114)	0.11973255528434235
  (20362, 932203)	0.11973255528434235
  (20362, 553967)	0.11973255528434235
  (20362, 121132)	0.11973255528434235
  (20362, 1071204)	0.11973255528434235
  (20362, 964141)	0.11973255528434235
  (20362, 391483)	0.11973255528434235
  (20362, 926620)	0.11973255528434235
  (20362, 881402)	0.11973255528434235
  (20362, 120712)	0.11973255528434235
  (20362, 256739)	0.11973255528434235
  (20362, 647165)	0.11973255528434235
  (20362, 477203)	0.11973255528434235
  (20362, 268972)	0.11973255528434235
  (20362, 137967)	0.11973255528434235
  (20362, 219136)	0.11973255528434235
  (20362, 284744)	0.11973255528434235

In [9]:
tfidf_matrix.shape

(20363, 1196254)

In [10]:
from sklearn.metrics.pairwise import linear_kernel

cosine_similarities = linear_kernel(tfidf_matrix, tfidf_matrix)

In [11]:
cosine_similarities.shape

(20363, 20363)

In [12]:
cosine_similarities[0].shape

(20363,)

In [13]:
df = df.reset_index()
titles = df['title']
titles.shape

(20363,)

In [14]:
indices = pd.Series(df.index, index=df['title'])

In [15]:
def recommend(title):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_similarities[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:31]
    movie_indices = [i[0] for i in sim_scores]
    return titles.iloc[movie_indices]

In [16]:
recommend('The Godfather').head(10)

15858    The Godfather: Part II
7198           Honor Thy Father
15604                The Family
2415                 Blood Ties
9280                       Made
8103         Johnny Dangerously
6034                       Fury
8980              Live by Night
12940            Shanghai Triad
7638     In Memory of My Father
Name: title, dtype: object

In [17]:
recommend('The Dark Knight Rises').head(10)

15305                       The Dark Knight
1821                         Batman Forever
1822                         Batman Returns
1831           Batman: Mask of the Phantasm
1815                                 Batman
1832        Batman: Mystery of the Batwoman
1837             Batman: Under the Red Hood
1819     Batman Beyond: Return of the Joker
1826                      Batman vs Dracula
1838                       Batman: Year One
Name: title, dtype: object